### ISSUE TITLE
required cmake version

### ISSUE THREAD

**Issue by mbennehar** [ethz-asl/libsbp_catkin#9]
Hi,
I wanted to build this package on ubuntu 16.04 and it doesn't seem to work with the default cmake version. The cmake command SOURCE_SUBDIR is not recognized. One easy solution is to upgrade cmake version via pip: [https://blog.kitware.com/cmake-python-wheels/](https://blog.kitware.com/cmake-python-wheels/)
Just wanted to point this out for those who run in the same problem and don't know where it comes from.

**Comment by rikba** [comment]
Thanks @mbennehar. If you have an alternative for SOURCE_SUBDIR feel free to push a commit. Otherwise your work around will probably do for others.
